prometheus:
  url: http://monitoring-kube-prometheus-prometheus.monitoring.svc
  port: 9090

# Expose our HTTP request-rate as a custom Pod metric so HPA can consume it.
# The `http_requests_total_per_second` name is derived from `http_requests_total` by the `name.as` template.
rules:
  default: false
  custom:
    - seriesQuery: 'http_requests_total{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
      name:
        matches: "^(.*)_total$"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
